# Generated by Django 3.1.4 on 2021-02-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20201207_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='owner',
        ),
    ]
